### ISSUE TITLE
Support iPad Swift Playgrounds

### ISSUE THREAD

**Issue by waliid** [SRGSSR/pillarbox-apple#593]
### Use case description

As a **user** of Pillarbox, I desire the capability to access the library on my iPad.

### Acceptance criteria

- Play streaming content on my iPad using Swift Playground.

### Proposed solution

Here are the steps to follow in order to be able to build on iPad:

- Remove comScore and tagCommander.
- Eliminate the plugins and binaryTargets.
- Don't use #Previews.

These changes should enable us to work effectively on iPad.

https://github.com/SRGSSR/pillarbox-apple/assets/3347810/16479fd6-808e-4521-82de-1e782a2e03e0

### Is there an existing similar feature request?

- [X] I have searched existing [features](https://github.com/SRGSSR/pillarbox-apple/issues?q=is%3Aissue+label%3Aenhancement+) and found no similar request.

- [X] I have browsed the available API and found no way to achieve the use case I described.

**Comment by Babyyoda777** [comment]
Hey did you end up making a fork or PoC? I can't get it to work on iPad either

**Comment by waliid** [comment]
> Hey did you end up making a fork or PoC? I can't get it to work on iPad either

Hi @Babyyoda777,

Actually, to make it works, I had to remove some dependencies as I explain in my proposed solution. At the moment I'm writing this message, the work has not been done yet.
However, we plan to separate the video player from the other dependencies very soon. So that the support for the playground will follow shortly after.

**Comment by Babyyoda777** [comment]
Hi thanks for that, is there any update on this? The Swift package manager seems to be completely broken for Pillarbox now though @waliid

**Comment by defagos** [comment]
Hi!

Swift Playground updates have not fixed the issue preventing packages with binaries such as Pillarbox to be integrated. Maybe this will happen with future Playground releases since WWDC is around the corner, but of course those won't be available until later this year.

Our mid-term goal is to completely separate the player component of Pillarbox into a dedicated universal playback-oriented package that gets rid of binary dependencies and our company-specific stuff. This sadly takes time and resources and, though we would love to provide Pillarbox player as a standalone playback library to the whole Apple community, there is currently not enough bandwidth for us to do the work at the moment I am afraid.

We'll of course keep you posted should we start working on that separation.
