### ISSUE TITLE
Documentation Request - Chapter / Segmented Videos

### ISSUE THREAD

**Issue by mutaben** [SRGSSR/pillarbox-apple#905]
### Use case description

I would like to have more information on integrating chapters and segmented videos aspects with a Pillarbox player please.

Thank you in advance.

### Is there an existing similar feature request?

- [X] I have searched existing [features](https://github.com/SRGSSR/pillarbox-apple/issues?q=is%3Aissue+label%3Aenhancement+) and found no similar request.

- [X] I have browsed the available API and found no way to achieve the use case I described.

**Comment by defagos** [comment]
Thanks for the suggestion. We could namely add a few words about chapter support in Pillarbox. Let me just briefly provide you with pointers until we have more documentation available.

# Terminology

A few words about terminology first, as we moved from an SRG SSR internal terminology with Letterbox (_chapters_ and _segments_) to a more standard one (_chapters_ only) with Pillarbox:

- Pillarbox only knows about _chapters_, which designate time ranges within a media content, possibly associated with standard metadata (title and image, most notably). A lot of SRG SSR video content provides _chapters_, e.g. a 19h30 or a 10vor10 is sliced into topics. Those topics are delivered in our metadata (media composition) and are exposed by Pillarbox as chapters for automatic display in the tvOS player UI. They are also available when building custom user experiences on iOS.
- Letterbox was previously supporting other related contents associated with some content being played, most notably in the radio area. These related contents are not representing time ranges into the content being played but are entirely different contents with their own URLs. Such related contents are not natively supported by Pillarbox anymore. Products can simply load related content themselves and use Pillarbox playlist support to present them in a cohesive way.

# Metadata

A Pillarbox `Player` is loaded with `PlayerItem`s, whose main purpose is to implement `Asset` delivery. An asset ultimately provides the URL of the content being played, alongside metadata. Standard metadata is exposed by `Player` through its `metadata` property. This property is automatically published by a `Player`, which means SwiftUI views can directly respond to metadata retrieval and adjust their layout accordingly.

Metadata is provided as `PlayerMetadata`. It most notably contains title, description and artworks for the content itself, and possibly a chapter list if available.

Our Core Business package provides `PlayerItem`s suitable for playing our content. If chapters are available they are automatically loaded and provided in updates published by a `Player` instance.

# Displaying chapters

Displaying chapters is therefore extremely easy in a custom iOS layout:

- Just read them from a player `metadata` property when building your layout.
- Use a `LazyImage` to load images (we namely avoid loading images if they are not used).
- Add an action so that when a user taps on a chapter the player seeks at it. A seek method is provided that accepts a `Chapter` directly.

The rest is entirely up to you. You can decide to display a chapter list horizontally or vertically, as a lateral or bottom pane, with or without images. Your creativity is the limit. See our [demo implementation](https://github.com/SRGSSR/pillarbox-apple/blob/main/Demo/Sources/Players/PlayerView.swift) for an example of integration.
